export const API_ENDPOINTS = {
    LATEST_PRODUCTS: 'product/latest',
    FEATURED_CATEGORIES: 'categories/featured',
    PRODUCTS: 'products',
    ALL_BRANDS: 'all-brands',
    STATES: 'states/64',
    CITIES: 'cities',
    AUTH: 'auth',
    REGISTER: 'auth/signup',
    LOGIN: 'auth/login',
    LOGOUT: 'auth/logout',
    USER: 'auth/user',
    CREATE_ADDRESS: 'user/address/create',
    ADDRESSES: 'user/addresses',
    ADD_TO_CART: 'carts/add',
    CREATE_ORDER: 'checkout/order/store',
    ORDER: 'user/order',
    REGISTER_SHOP: 'shop/register',
    USER_ORDERS: 'user/orders',
};
